Test de la fonction ``nteger_validator`` en Python
======================

Cette fonction divise tous les éléments d'une matice
-------------------
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


>>> BaseGeometry.integer_validator(BaseGeometry, "age", 0)
Traceback (most recent call last):
  ...
ValueError: age must be greater than 0

>>> BaseGeometry.integer_validator(BaseGeometry, "distance", -4)
Traceback (most recent call last):
  ...
ValueError: distance must be greater than 0

>>> bg = BaseGeometry()
>>> isinstance(bg, BaseGeometry)
True

>>> hasattr(BaseGeometry, 'area')
True

>>> BaseGeometry.integer_validator("age", 1)
Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 7-base_geometry.txt[6]>", line 1, in <module>
        BaseGeometry.integer_validator("age", 1)
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> BaseGeometry.integer_validator("age", True)
Traceback (most recent call last):
  ...
TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'